language: node_js
node_js:
  - "node"
branches:
  only:
    - test
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - npm install -g sequelize-cli
  - npm run migration
services:
  - postgresql
script:
  - npm test
env:
  - NODE_ENV=test
addons:
  postgresql: "9.3"
after_success:
  - npm run coveralls
