language: node_js
node_js:
  - "node"
branches:
  only:
    - test
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - psql -c 'create database waleDB;' -U postgres
  - babel-node app.js
services:
  -postgresql
script:
  - npm test
env:
  - NODE_ENV=test
