language: node_js
node_js:
  - "node"
branches:
  only:
    - test
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - psql -U postgres -c 'create database waleDB;' 
  - pg_sleep(10);
services:
  -postgresql
script:
  - npm test
env:
  - NODE_ENV=test
