language: node_js
node_js:
  - "node"
branches:
  only:
    - test
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - npm install -g sequelize-cli
  - psql -w -c 'create database waleDB;' -U postgres 
  - npm run migrate-test
services:
  -postgresql
script:
  - npm test
env:
  - NODE_ENV=test
  - TRAVIS=traviz CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
