language: node_js
node_js:
  - "node"
branches:
  only:
    - test
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - npm install -g sequelize-cli
  - psql -c 'drop database if exists waleDB;' -U postgres
  - psql -c 'create database waleDB;' -U postgres 
  - npm run migrate
services:
  - postgresql
script:
  - npm test
env:
  - NODE_ENV=test
