language: node_js
node_js:
  - "node"
branches:
  only:
    - test
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - psql -c 'CREATE DATABASE waleDB;' -U postgres
services:
  -postgresql
script:
  - npm run format && npm test
env:
  - NODE_ENV=test
