 
import jwt from 'jsonwebtoken';

const secrete = process.env.SECRETE;

export default {
  checkForToken(req, res, next){
//Fist check if the user has been authorised by looking for a token generated by jwt
    const token = req.body.token || req.query.token || req.header['x-access-token'];
    if (!token) {
      return res.status(401).send({message: 'User not authorised'});
    } else{
//If there is a token then verify the token is authentic i.e. was generated from the jwt of this app.
      jwt.verify(token, secrete, (err, decodedToken) =>{
        if (err) {
          return res.status(401).send({message: 'Authentication failed'});
        } else{
          req.decoded = decodedToken;
          next();
        } //end of inner else statement
      });
    }// end of outter else statement
  }, //end of check for token function
}; //end of export default